update automated formatting

diff --git a/.github/workflows/formatter.yml b/.github/workflows/formatter.yml
--- a/.github/workflows/formatter.yml
+++ b/.github/workflows/formatter.yml
@@ -64,12 +64,13 @@ jobs:
               run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
               
             - name: Push branch
-              run:
-                git push origin auto/code-formatting-${{ env.BRANCH_SUFFIX }}
+              run: |
+                git push origin auto/code-formatting-${{ env.BRANCH_SUFFIX }} || (echo "Push failed!" && exit 1)
 
             - name: Create PR
               run: |
-               gh pr create --base main --head auto/code-formatting-${{ env.BRANCH_SUFFIX }} --title "Apply formatting to main branch"
-            
+                gh pr list --base main --head auto/code-formatting-${{ env.BRANCH_SUFFIX }} | grep "auto/code-formatting-${{ env.BRANCH_SUFFIX }}" && echo "PR already exists" || \
+                gh pr create --base main --head auto/code-formatting-${{ env.BRANCH_SUFFIX }} --title "Apply formatting to main branch"
               env:
-                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+              
